### ISSUE TITLE
[FEAT] 유저 검색 기능

### ISSUE THREAD

**Issue by gyulls2** [FRONTENDSCHOOL7/villains#101]
## Description
피드 페이지 헤더에 유저 검색 기능을 추가합니다.

###  API 명세서

- [노션 링크](https://mammoth-sassafras-ff5.notion.site/0b357fd6245d45a2a514145dd6d46f5d?pvs=4)

## ToDo
- [x] 피드에서 검색 버튼을 눌렀을 때 검색 필드 노출
- [x] 유저 검색 api 호출
- [ ] 검색된 유저 클릭 시 해당 유저의 프로필 페이지로 이동
- [ ] 관리자는 검색에서 제외
