### ISSUE TITLE
[FEAT] 스플래시 페이지

### ISSUE THREAD

**Issue by kys0417** [FRONTENDSCHOOL7/VILLAINS#14]
## Description
스플래시 페이지를 구현합니다.

###  API 명세서

- [노션 링크](https://mammoth-sassafras-ff5.notion.site/c7a2df950be14f0ead23ee7307157db6?pvs=4)

## ToDo
- [x] 1초동안 보여주는 스플래시 페이지 구현
- [x] 이메일 로그인, SNS 로그인 버튼 구현
- [x] SNS 로그인 버튼 disabled
- [x] 회원가입 버튼 구현
