### ISSUE TITLE
[REFACTOR] 버튼 컴포넌트 수정 작업

### ISSUE THREAD

**Issue by Sleepingoff** [FRONTENDSCHOOL7/villains#162]
## Description
기존 아이콘을 svg에서 컴포넌트로 교체 후 생기는 문제로 보입니다.
IconButton 컴포넌트에서 백그라운드 이미지를 찾을 수 없어 생기는 문제
기존 코드
```
const IconBtn = ({ text, onClick, disabled, img }) => {
  const handleClick = (event) => {
    event.preventDefault();
  };
  return (
    <IconButton onClick={onClick ?? handleClick} disabled={disabled ?? false} img={img}>
      {text}
    </IconButton>
  );
};
```
기존 코드에서 이메일 아이콘의 경우 크기 조절로 인해 분기처리를 해주었습니다. 
img는 경로가 아닌 텍스트로 받고 있던 것으로 확인했습니다.

변경할 코드
```
const IconBtn = ({ children, onClick, disabled}) => {
  const handleClick = (event) => {
    event.preventDefault();
  };
  return (
    <IconButton onClick={onClick ?? handleClick} disabled={disabled ?? false}>
      {children}
    </IconButton>
  );
};
```

## ToDo
- [ ] 기존 IconBtn 코드 수정
- [ ] 사용한 곳에서 이미지 prop 삭제 후 children으로 교체
- [ ] UI 확인 후 수정
